version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: nextjs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c  
      MYSQL_DATABASE: my_database       
      MYSQL_USER: user                  
      MYSQL_PASSWORD: password          
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: